name: base_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+4

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


 # ****************** Network **********************
#  dio_helper: ^1.1.8 ///tarek Package
  dio: ^4.0.6
  # ***************** SQLite **********************
  crypto: ^3.0.2
  path: ^1.8.0
  quiver: ^3.1.0
  sqflite: ^2.0.2+1
  # **************** NoSQLite ***************************
  shared_preferences: ^2.0.15
  # **************** fireBase & Fcm **********************
#  firebase_messaging: ^11.4.2
#  firebase_core: ^1.20.1
#  flutter_local_notifications: ^9.6.1
#  firebase_core_platform_interface: 4.5.1
  # *************** Maps &Locations ***********************
  google_maps_flutter: ^2.2.0
  geocoding: ^2.0.5
  geolocator: ^9.0.1
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^1.3.0
  material_floating_search_bar: ^0.3.7
  map_launcher: ^2.4.0
  #  geocode: ^1.0.2
  #  location: ^4.4.0
  #  geocoder:
  #  flutter_google_places: ^0.3.0
  #  google_maps_place_picker:

  # **************** state Management ***************
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
#  auto_route: ^4.0.1
  flutter_launcher_icons: ^0.10.0
  url_launcher: ^6.1.5
  # **************** Utils ***************************
#  modal_bottom_sheet: ^2.1.2
#  tf_custom_widgets: ^1.1.14
  flutter_staggered_animations: ^1.0.0
  liquid_pull_to_refresh: ^3.0.1
  equatable: ^2.0.5
  flutter_spinkit: ^5.1.0
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.9
  tf_validator: ^0.0.2
  photo_view: ^0.14.0
  intl: ^0.17.0
  flutter_easyloading: ^3.0.5
  percent_indicator: ^4.2.2
#  flutter_phoenix: ^1.0.0
#  flutter_swiper: ^1.1.6
  share: ^2.0.4
  flutter_rounded_date_picker: ^3.0.2
  material_design_icons_flutter: ^5.0.6996
  flutter_html: ^2.2.1
  animations: ^2.0.2
  pin_code_fields: ^7.4.0
  image_picker: ^0.8.5+3
  flutter_svg: ^0.23.0+1
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  platform: ^3.1.0
  device_preview: ^1.1.0
  shimmer: ^2.0.0
  video_player: ^2.5.1
  timeline_tile: ^2.0.0
  path_provider: ^2.0.14
  flutter_inappwebview: ^5.7.2+3
  lazy_load_scrollview: ^1.3.0
  syncfusion_flutter_pdfviewer:

# can use it:
#  flutter_rating_bar: ^4.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/LogoBlue.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
#  auto_route_generator: ^4.0.0
  build_runner: ^2.2.0
#  flutter_native_splash:
#flutter_native_splash:
#  image: assets/images/fav.png
#  color: "#2885BF"
#  android: true
#  ios: false

flutter_assets_generator:
  # Optional. Sets the directory of generated localization files. Provided value should be a valid path on lib dir. Default: generated
  output_dir: res
  # Optional. Sets whether utomatic monitoring of file changes. Default: true
  auto_detection: true
  # Optional. Sets file name conversion rules. Default: true
  named_with_parent: true
  # Optional. Sets the name for the generated localization file. Default: assets
  output_filename: res
  # Optional. Sets the name for the generated localization class. Default: Assets
  class_name: Res
  # Optional. Sets the filename split pattern for filename split. Default: [-_]
  filename_split_pattern: "[-_]"
  # to generate asset just click alt + g




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/anim/
    - assets/images/
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: URW DIN Arabic
#      fonts:
#        - asset: assets/fonts/URW DIN Arabic Bold.ttf
#          weight: 700
#        - asset: assets/fonts/URW DIN Arabic Light.ttf
#          weight: 400
#        - asset: assets/fonts/URW DIN Arabic Thin.ttf
#          weight: 200
#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
