name: base_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


 # ****************** Network **********************
#  dio_helper: ^1.1.8 ///tarek Package
  dio: ^4.0.4
  # ***************** SQLite **********************
  crypto: ^3.0.1
  path: ^1.8.0
  quiver: ^3.0.1+1
  sqflite: ^2.0.0+4
  # **************** NoSQLite ***************************
  shared_preferences: ^2.0.13
  # **************** fireBase & Fcm **********************
  firebase_messaging: ^11.2.6
  firebase_core: ^1.12.0
  flutter_local_notifications: ^9.3.2
  # *************** Maps &Locations ***********************
  google_maps_flutter: ^2.0.11
  location: ^4.3.0
  geolocator:
  geocoder:
  geocode: ^1.0.1
  #  flutter_google_places: ^0.3.0
  #  google_maps_place_picker:
  flutter_google_places:
  google_maps_webservice:
  google_api_headers: ^1.1.1
  material_floating_search_bar: ^0.3.7
  map_launcher: ^2.2.1+1
  # **************** state Management ***************
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  auto_route: ^3.2.3+1
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.20
  # **************** Utils ***************************
  modal_bottom_sheet: ^2.0.0
#  tf_custom_widgets: ^1.1.14
  flutter_staggered_animations: ^1.0.0
  liquid_pull_to_refresh: ^3.0.1
  equatable: ^2.0.3
  flutter_spinkit: ^5.1.0
  google_fonts: ^2.3.1
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.8
  tf_validator: ^0.0.2
  photo_view: ^0.13.0
  intl: ^0.17.0
  flutter_easyloading: ^3.0.3
  flutter_phoenix: ^1.0.0
  flutter_swiper: ^1.1.6
  share: ^2.0.4
  flutter_rounded_date_picker: ^2.0.2
  material_design_icons_flutter: ^5.0.6595
  flutter_html: ^2.2.1
  pin_code_fields: ^7.3.0
  image_picker: ^0.8.4+9
  flutter_svg: ^0.23.0+1
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  platform: ^3.1.0






# can use it:
#  flutter_rating_bar: ^4.0.0



flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.0
  build_runner: ^2.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/anim/api_empty.json
    - assets/anim/api_error.json
    - assets/anim/delivery.json
    - assets/anim/empty_cart.json
    - assets/anim/success.json
    - assets/images/america.png
    - assets/images/appIcon.png
    - assets/images/arrow.png
    - assets/images/arrow_forward.png
    - assets/images/calendar.png
    - assets/images/call.png
    - assets/images/camera-1.png
    - assets/images/camera-2.png
    - assets/images/camera.png
    - assets/images/check.png
    - assets/images/check_circle.png
    - assets/images/discount.gif
    - assets/images/edit.png
    - assets/images/facebook.png
    - assets/images/fav.png
    - assets/images/favPress.PNG
    - assets/images/favPressed.png
    - assets/images/favUnPress.PNG
    - assets/images/fire_empty.png
    - assets/images/fire_fill.png
    - assets/images/following.png
    - assets/images/Group.png
    - assets/images/hands.png
    - assets/images/home_empty.png
    - assets/images/home_fill.png
    - assets/images/icon.png
    - assets/images/Iconly-Light-Location.png
    - assets/images/instagram.png
    - assets/images/linkedin.png
    - assets/images/location.png
    - assets/images/logo.png
    - assets/images/logo4.svg
    - assets/images/logoIcon.png
    - assets/images/logoIcon1.png
    - assets/images/logout.png
    - assets/images/Logout1.png
    - assets/images/Mada_Logo.png
    - assets/images/marker.png
    - assets/images/master-card.png
    - assets/images/more_empty.png
    - assets/images/more_fill.png
    - assets/images/nodata.png
    - assets/images/notification.png
    - assets/images/placeholder.png
    - assets/images/plus.png
    - assets/images/saudi-arabia.png
    - assets/images/search.png
    - assets/images/splash.png
    - assets/images/switch1.png
    - assets/images/time.png
    - assets/images/twitter.png
    - assets/images/visa.png
    - assets/images/visibility.png
    - assets/lang/ar.json
    - assets/lang/en.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
